version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend
    ports:
      - 3001:3001
    environment:
      CHAT_DB: mongodb://mikhail:secretcat@mongodb:27017/chat
      JWT_SIGN_KEY: 'secretcat'

  mongo:
    image: 'mongo'
    container_name: 'mongodb'
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db

